/**
 * Verification against the illustrative examples of IS 10262 : 2019.
 *
 * Each case carries the stipulations and test data exactly as printed in
 * the annex, together with the values the standard itself arrives at.
 * The engine is run on those inputs and the two sets are compared, so
 * the calculator can be shown to reproduce the standard.
 *
 * Annex A  M 40, PPC, no mineral admixture       clause 5.9
 * Annex B  M 40, OPC 43 with fly ash             clause 5.9
 * Annex C  M 40, OPC 43 with GGBS                clause 5.9
 * Annex D  M 70, OPC 53 with silica fume and fly ash   clause 6.3
 * Annex E  M 30 self compacting concrete with fly ash  clause 8.4
 * Annex F  M 15 mass concrete, 150 mm aggregate        clause 9.13
 */

import { designMix, defaultInput } from './mixDesign.js';
import { designSCC } from './sccDesign.js';

const ANNEX_A = {
  id: 'A',
  title: 'Annex A — M 40 with PPC',
  clause: 'Clause 5.9',
  summary:
    'Ordinary and standard grade procedure with no mineral admixture. Aggregates first taken in the saturated surface dry condition, then corrected for the dry condition in A-11.',
  input: {
    section: 'ordinary',
    project: 'IS 10262 : 2019, Annex A',
    fck: 40,
    concreteType: 'reinforced',
    cementType: 'ppc',
    cementSG: 2.88,
    exposure: 'severe',
    msa: 20,
    slump: 75,
    placing: 'chute',
    siteControl: 'good',
    sdMode: 'table',
    caShape: 'angular',
    faZone: 'II',
    faType: 'natural',
    caSG: 2.74,
    faSG: 2.65,
    caAbsorption: 0.5,
    faAbsorption: 1.0,
    aggCondition: 'dry',
    chemType: 'superplasticizer',
    chemDosage: 1.0,
    chemWaterReduction: 23,
    chemSG: 1.145,
    mineralType: 'none',
    secondMineralType: 'none',
    increaseCementitious: false,
    wcMode: 'manual',
    wcManual: 0.36,
    airMode: 'table',
    caVolMode: 'table',
    pumpableReduction: 0,
    maxCement: 450,
    roundCementitious: 'up',
    aggVolDp: 3,
    caVolDp: 'auto',
  },
  expected: [
    { label: "Target mean strength f'ck", ref: 'A-3', std: 48.25, unit: 'N/mm²', get: (o) => o.targetStrength, tol: 0.01 },
    { label: 'Entrapped air', ref: 'A-4', std: 1.0, unit: '%', get: (o) => o.airPct, tol: 0.001 },
    { label: 'Free water-cement ratio', ref: 'A-5', std: 0.36, unit: '', get: (o) => o.wc, tol: 0.001 },
    { label: 'Water content', ref: 'A-6', std: 148, unit: 'kg/m³', get: (o) => o.water, tol: 0 },
    { label: 'Cement content', ref: 'A-7', std: 412, unit: 'kg/m³', get: (o) => o.ssd.cement, tol: 0 },
    { label: 'Volume of coarse aggregate per unit volume of total aggregate', ref: 'A-8', std: 0.648, unit: '', get: (o) => o.caVolFraction, tol: 0.001 },
    { label: 'Volume of fine aggregate', ref: 'A-8', std: 0.352, unit: '', get: (o) => o.faVolFraction, tol: 0.001 },
    { label: 'Volume of all in aggregate', ref: 'A-9 (g)', std: 0.695, unit: 'm³', get: (o) => o.volumes.vAgg, tol: 0.0006 },
    { label: 'Coarse aggregate, SSD', ref: 'A-9 (h)', std: 1234, unit: 'kg/m³', get: (o) => o.ssd.ca, tol: 0 },
    { label: 'Fine aggregate, SSD', ref: 'A-9 (j)', std: 648, unit: 'kg/m³', get: (o) => o.ssd.fa, tol: 0 },
    { label: 'Chemical admixture', ref: 'A-10', std: 4.12, unit: 'kg/m³', get: (o) => o.ssd.chem, tol: 0.005 },
    { label: 'Fine aggregate, dry', ref: 'A-11 (a)', std: 642, unit: 'kg/m³', get: (o) => o.field.fa, tol: 0 },
    { label: 'Coarse aggregate, dry', ref: 'A-11 (b)', std: 1228, unit: 'kg/m³', get: (o) => o.field.ca, tol: 0 },
    { label: 'Water to be added', ref: 'A-12', std: 160, unit: 'kg/m³', get: (o) => o.field.water, tol: 0 },
  ],
};

const ANNEX_B = {
  id: 'B',
  title: 'Annex B — M 40 with fly ash',
  clause: 'Clause 5.9',
  summary:
    'Fly ash as part replacement of OPC 43, with the 10 percent increase in cementitious content of clause 5.4.1, a 10 percent reduction of coarse aggregate for pumping, and aggregates in the wet condition.',
  input: {
    section: 'ordinary',
    project: 'IS 10262 : 2019, Annex B',
    fck: 40,
    concreteType: 'reinforced',
    cementType: 'opc43',
    cementSG: 3.15,
    exposure: 'severe',
    msa: 20,
    slump: 120,
    placing: 'pumping',
    siteControl: 'good',
    sdMode: 'table',
    caShape: 'angular',
    faZone: 'II',
    faType: 'natural',
    caSG: 2.74,
    faSG: 2.65,
    caAbsorption: 0.5,
    faAbsorption: 1.0,
    aggCondition: 'wet',
    caMoisture: 2.0,
    faMoisture: 5.0,
    chemType: 'superplasticizer',
    chemDosage: 1.0,
    chemWaterReduction: 23,
    chemSG: 1.145,
    mineralType: 'flyAsh',
    mineralPct: 30,
    mineralSG: 2.2,
    secondMineralType: 'none',
    increaseCementitious: true,
    increaseCementitiousPct: 10,
    wcMode: 'manual',
    wcManual: 0.36,
    airMode: 'table',
    caVolMode: 'table',
    pumpableReduction: 10,
    maxCement: 450,
    roundCementitious: 'up',
    aggVolDp: 3,
    caVolDp: 'auto',
  },
  expected: [
    { label: "Target mean strength f'ck", ref: 'B-3', std: 48.25, unit: 'N/mm²', get: (o) => o.targetStrength, tol: 0.01 },
    { label: 'Water content', ref: 'B-6', std: 155, unit: 'kg/m³', get: (o) => o.water, tol: 0 },
    { label: 'Cementitious materials content', ref: 'B-7', std: 474, unit: 'kg/m³', get: (o) => o.cementitious, tol: 0 },
    { label: 'Free water-cementitious materials ratio', ref: 'B-7', std: 0.327, unit: '', get: (o) => o.wcm, tol: 0.001 },
    { label: 'Fly ash at 30 percent', ref: 'B-7', std: 142, unit: 'kg/m³', get: (o) => o.ssd.mineral1, tol: 0.3 },
    { label: 'Cement (OPC) content', ref: 'B-7', std: 332, unit: 'kg/m³', get: (o) => o.ssd.cement, tol: 0.3 },
    { label: 'Volume of coarse aggregate', ref: 'B-8', std: 0.59, unit: '', get: (o) => o.caVolFraction, tol: 0.001 },
    { label: 'Coarse aggregate, SSD', ref: 'B-9 (h)', std: 1069, unit: 'kg/m³', get: (o) => o.ssd.ca, tol: 2 },
    { label: 'Fine aggregate, SSD', ref: 'B-9 (j)', std: 719, unit: 'kg/m³', get: (o) => o.ssd.fa, tol: 2 },
    { label: 'Chemical admixture', ref: 'B-10', std: 4.74, unit: 'kg/m³', get: (o) => o.ssd.chem, tol: 0.005 },
    { label: 'Fine aggregate, wet', ref: 'B-11 (a)', std: 748, unit: 'kg/m³', get: (o) => o.field.fa, tol: 2 },
    { label: 'Coarse aggregate, wet', ref: 'B-11 (b)', std: 1085, unit: 'kg/m³', get: (o) => o.field.ca, tol: 2 },
    { label: 'Water to be added', ref: 'B-12', std: 110, unit: 'kg/m³', get: (o) => o.field.water, tol: 1 },
  ],
};

const ANNEX_C = {
  id: 'C',
  title: 'Annex C — M 40 with GGBS',
  clause: 'Clause 5.9',
  summary:
    'GGBS at 40 percent of total cementitious material, with no increase in cementitious content, a 10 percent reduction of coarse aggregate for pumping, and aggregates in the saturated surface dry condition.',
  input: {
    section: 'ordinary',
    project: 'IS 10262 : 2019, Annex C',
    fck: 40,
    concreteType: 'reinforced',
    cementType: 'opc43',
    cementSG: 3.15,
    exposure: 'severe',
    msa: 20,
    slump: 120,
    placing: 'pumping',
    siteControl: 'good',
    sdMode: 'table',
    caShape: 'angular',
    faZone: 'II',
    faType: 'natural',
    caSG: 2.74,
    faSG: 2.65,
    caAbsorption: 0.5,
    faAbsorption: 1.0,
    aggCondition: 'ssd',
    chemType: 'superplasticizer',
    chemDosage: 1.0,
    chemWaterReduction: 23,
    chemSG: 1.145,
    mineralType: 'ggbs',
    mineralPct: 40,
    mineralSG: 3.0,
    secondMineralType: 'none',
    increaseCementitious: false,
    wcMode: 'manual',
    wcManual: 0.36,
    airMode: 'table',
    caVolMode: 'table',
    pumpableReduction: 10,
    maxCement: 450,
    roundCementitious: 'up',
    aggVolDp: 4,
    caVolDp: 'auto',
  },
  expected: [
    { label: "Target mean strength f'ck", ref: 'C-3', std: 48.25, unit: 'N/mm²', get: (o) => o.targetStrength, tol: 0.01 },
    { label: 'Water content', ref: 'C-6', std: 155, unit: 'kg/m³', get: (o) => o.water, tol: 0 },
    { label: 'Cementitious materials content', ref: 'C-7', std: 431, unit: 'kg/m³', get: (o) => o.cementitious, tol: 0 },
    { label: 'GGBS at 40 percent', ref: 'C-7', std: 172, unit: 'kg/m³', get: (o) => o.ssd.mineral1, tol: 0.5 },
    { label: 'Cement (OPC) content', ref: 'C-7', std: 259, unit: 'kg/m³', get: (o) => o.ssd.cement, tol: 0.5 },
    { label: 'Volume of coarse aggregate', ref: 'C-8', std: 0.58, unit: '', get: (o) => o.caVolFraction, tol: 0.001 },
    { label: 'Volume of total aggregate', ref: 'C-9 (g)', std: 0.6917, unit: 'm³', get: (o) => o.volumes.vAgg, tol: 0.0002 },
    { label: 'Coarse aggregate, SSD', ref: 'C-9 (h)', std: 1099, unit: 'kg/m³', get: (o) => o.ssd.ca, tol: 2 },
    { label: 'Fine aggregate, SSD', ref: 'C-9 (j)', std: 770, unit: 'kg/m³', get: (o) => o.ssd.fa, tol: 2 },
    { label: 'Chemical admixture', ref: 'C-10', std: 4.31, unit: 'kg/m³', get: (o) => o.ssd.chem, tol: 0.005 },
  ],
};

const ANNEX_D = {
  id: 'D',
  title: 'Annex D — M 70 high strength',
  clause: 'Clause 6.3',
  summary:
    'High strength procedure of Section 3, with silica fume at 5 percent and fly ash at 15 percent, the w/cm taken from Table 8 and a PCE based superplasticizer reducing water by 30 percent.',
  input: {
    section: 'highStrength',
    project: 'IS 10262 : 2019, Annex D',
    fck: 70,
    concreteType: 'reinforced',
    cementType: 'opc53',
    cementSG: 3.15,
    exposure: 'severe',
    msa: 20,
    slump: 120,
    placing: 'pumping',
    siteControl: 'good',
    sdMode: 'table',
    caShape: 'angular',
    faZone: 'II',
    faType: 'natural',
    caSG: 2.74,
    faSG: 2.65,
    caAbsorption: 0.5,
    faAbsorption: 1.0,
    aggCondition: 'ssd',
    chemType: 'pce',
    chemDosage: 0.5,
    chemWaterReduction: 30,
    chemSG: 1.08,
    mineralType: 'flyAsh',
    mineralPct: 15,
    mineralSG: 2.2,
    secondMineralType: 'silicaFume',
    secondMineralPct: 5,
    secondMineralSG: 2.2,
    increaseCementitious: true,
    increaseCementitiousPct: 10,
    wcMode: 'auto',
    wcRoundDp: 2,
    airMode: 'table',
    caVolMode: 'table',
    pumpableReduction: 0,
    maxCement: 450,
    roundCementitious: 'nearest',
    aggVolDp: 3,
    caVolDp: 'auto',
  },
  expected: [
    { label: "Target mean strength f'ck", ref: 'D-3', std: 79.9, unit: 'N/mm²', get: (o) => o.targetStrength, tol: 0.01 },
    { label: 'Entrapped air', ref: 'D-4', std: 0.5, unit: '%', get: (o) => o.airPct, tol: 0.001 },
    { label: 'Water-cementitious materials ratio from Table 8', ref: 'D-5', std: 0.29, unit: '', get: (o) => o.wcSelected, tol: 0.001 },
    { label: 'Water content', ref: 'D-6', std: 141, unit: 'kg/m³', get: (o) => o.water, tol: 0 },
    { label: 'Cementitious materials content', ref: 'D-7', std: 535, unit: 'kg/m³', get: (o) => o.cementitious, tol: 0 },
    { label: 'Fly ash at 15 percent', ref: 'D-7', std: 80.25, unit: 'kg/m³', get: (o) => o.ssd.mineral1, tol: 0.5 },
    { label: 'Silica fume at 5 percent', ref: 'D-7', std: 26.75, unit: 'kg/m³', get: (o) => o.ssd.mineral2, tol: 0.5 },
    { label: 'Cement (OPC) content', ref: 'D-7', std: 428, unit: 'kg/m³', get: (o) => o.ssd.cement, tol: 0.5 },
    { label: 'Revised w/cm', ref: 'D-7', std: 0.264, unit: '', get: (o) => o.wcm, tol: 0.001 },
    { label: 'Volume of coarse aggregate', ref: 'D-8', std: 0.667, unit: '', get: (o) => o.caVolFraction, tol: 0.001 },
    { label: 'Volume of fine aggregate', ref: 'D-8', std: 0.333, unit: '', get: (o) => o.faVolFraction, tol: 0.001 },
    { label: 'Volume of all in aggregate', ref: 'D-9 (h)', std: 0.667, unit: 'm³', get: (o) => o.volumes.vAgg, tol: 0.0006 },
    { label: 'Coarse aggregate, SSD', ref: 'D-9 (j)', std: 1219, unit: 'kg/m³', get: (o) => o.ssd.ca, tol: 1 },
    { label: 'Fine aggregate, SSD', ref: 'D-9 (k)', std: 589, unit: 'kg/m³', get: (o) => o.ssd.fa, tol: 1 },
    { label: 'Chemical admixture', ref: 'D-9.1', std: 2.675, unit: 'kg/m³', get: (o) => o.ssd.chem, tol: 0.05 },
  ],
};

const ANNEX_E = {
  id: 'E',
  title: 'Annex E — M 30 self compacting',
  clause: 'Clause 8.4',
  summary:
    'Section 4 procedure: water content and powder content chosen from the typical ranges of clause 8.3, the fine aggregate sized to supply the powder the cementitious material does not, and the coarse aggregate found by subtraction. The standard rounds each component volume before subtracting, which moves its coarse aggregate about 3 kg above the unrounded figure.',
  input: {
    section: 'scc',
    project: 'IS 10262 : 2019, Annex E',
    fck: 30,
    concreteType: 'reinforced',
    cementType: 'opc43',
    cementSG: 3.15,
    exposure: 'severe',
    msa: 20,
    siteControl: 'good',
    sdMode: 'table',
    caShape: 'angular',
    faZone: 'II',
    faType: 'natural',
    caSG: 2.74,
    faSG: 2.65,
    caAbsorption: 0.5,
    faAbsorption: 1.0,
    aggCondition: 'ssd',
    chemType: 'pce',
    chemDosage: 0.6,
    chemSG: 1.08,
    mineralType: 'flyAsh',
    mineralPct: 35,
    mineralSG: 2.2,
    secondMineralType: 'none',
    sccWater: 190,
    sccPowder: 520,
    sccFaFinesPct: 8,
    slumpFlowClass: 'SF3',
    viscosityClass: 'V1',
    segregationClass: 'SR1',
    lBoxRatio: 0.9,
    vmaDosage: 0,
    wcMode: 'manual',
    wcManual: 0.43,
    airMode: 'table',
    maxCement: 450,
    roundCementitious: 'up',
    aggVolDp: 3,
  },
  expected: [
    { label: "Target mean strength f'ck", ref: 'E-3', std: 38.25, unit: 'N/mm²', get: (o) => o.targetStrength, tol: 0.01 },
    { label: 'Entrapped air', ref: 'E-4', std: 1.0, unit: '%', get: (o) => o.airPct, tol: 0.001 },
    { label: 'Free water-cement ratio', ref: 'E-5', std: 0.43, unit: '', get: (o) => o.wc, tol: 0.001 },
    { label: 'Water content', ref: 'E-7.1', std: 190, unit: 'kg/m³', get: (o) => o.water, tol: 0 },
    { label: 'Cementitious materials content', ref: 'E-7.1', std: 442, unit: 'kg/m³', get: (o) => o.cementitious, tol: 0 },
    { label: 'Fly ash at 35 percent', ref: 'E-7.1', std: 155, unit: 'kg/m³', get: (o) => o.ssd.mineral1, tol: 0.5 },
    { label: 'Cement (OPC) content', ref: 'E-7.1', std: 287, unit: 'kg/m³', get: (o) => o.ssd.cement, tol: 0.5 },
    { label: 'Superplasticizer at 0.6 percent', ref: 'E-7.2', std: 2.65, unit: 'kg/m³', get: (o) => o.ssd.chem, tol: 0.005 },
    { label: 'Powder to be contributed by fine aggregate', ref: 'E-7.3', std: 78, unit: 'kg/m³', get: (o) => o.scc.finesFromFA, tol: 0 },
    { label: 'Fine aggregate, SSD', ref: 'E-7.3', std: 975, unit: 'kg/m³', get: (o) => o.ssd.fa, tol: 0 },
    { label: 'Volume of coarse aggregate', ref: 'E-7.4', std: 0.269, unit: 'm³', get: (o) => o.volumes.vCA, tol: 0.0015 },
    { label: 'Coarse aggregate, SSD', ref: 'E-7.4', std: 737, unit: 'kg/m³', get: (o) => o.ssd.ca, tol: 4 },
    { label: 'Volume of powder content', ref: 'E-7.5', std: 0.191, unit: 'm³', get: (o) => o.scc.vPowder, tol: 0.0005 },
    { label: 'Water to powder ratio by volume', ref: 'E-7.5', std: 0.99, unit: '', get: (o) => o.scc.waterPowderRatio, tol: 0.01 },
  ],
};

const ANNEX_F = {
  id: 'F',
  title: 'Annex F — M 15 mass concrete',
  clause: 'Clause 9.13',
  summary:
    'Section 5 procedure for 150 mm rounded aggregate in plain concrete: the 25 percent wet sieving uplift of clause 9.2 on the cube target, water from Table 12 less 10 kg for rounded gravel, a 15 percent increase in cementitious content for fly ash, coarse aggregate volume from Table 13, and the mortar content check of Table 15. The water-cement ratio is left to the Figure 1 lookup, where the durability limit governs.',
  input: {
    section: 'mass',
    project: 'IS 10262 : 2019, Annex F',
    fck: 15,
    concreteType: 'plain',
    cementType: 'opc43',
    cementSG: 3.15,
    exposure: 'moderate',
    msa: 150,
    slump: 50,
    siteControl: 'good',
    sdMode: 'table',
    caShape: 'roundedGravel',
    faZone: 'II',
    faType: 'natural',
    caSG: 2.74,
    faSG: 2.65,
    caAbsorption: 0.5,
    faAbsorption: 1.0,
    aggCondition: 'ssd',
    chemType: 'none',
    chemDosage: 0,
    chemWaterReduction: 0,
    mineralType: 'flyAsh',
    mineralPct: 25,
    mineralSG: 2.2,
    secondMineralType: 'none',
    increaseCementitious: true,
    increaseCementitiousPct: 15,
    airEntrained: false,
    wcMode: 'auto',
    wcRoundDp: 2,
    airMode: 'table',
    caVolMode: 'table',
    pumpableReduction: 0,
    maxCement: 450,
    roundCementitious: 'up',
    aggVolDp: 4,
    caVolDp: 'auto',
  },
  expected: [
    { label: "Target mean strength f'ck", ref: 'F-3', std: 20.77, unit: 'N/mm²', get: (o) => o.targetStrength, tol: 0.011 },
    { label: 'Target for cube tests, with 25 percent uplift', ref: 'F-3', std: 26.0, unit: 'N/mm²', get: (o) => o.targetStrengthCubes, tol: 0.05 },
    { label: 'Entrapped air', ref: 'F-4', std: 0.2, unit: '%', get: (o) => o.airPct, tol: 0.001 },
    { label: 'Free w/c read from Figure 1, before the durability limit', ref: 'F-5', std: 0.61, unit: '', get: (o) => o.wcSelected, tol: 0.011 },
    { label: 'Free water-cement ratio adopted', ref: 'F-5', std: 0.6, unit: '', get: (o) => o.wc, tol: 0.001 },
    { label: 'Water content', ref: 'F-6', std: 115, unit: 'kg/m³', get: (o) => o.water, tol: 0 },
    { label: 'Cementitious materials content', ref: 'F-7', std: 221, unit: 'kg/m³', get: (o) => o.cementitious, tol: 0 },
    { label: 'Free water-cementitious materials ratio', ref: 'F-7', std: 0.52, unit: '', get: (o) => o.wcm, tol: 0.001 },
    { label: 'Fly ash at 25 percent', ref: 'F-7', std: 55, unit: 'kg/m³', get: (o) => o.ssd.mineral1, tol: 0.5 },
    { label: 'Cement (OPC) content', ref: 'F-7', std: 166, unit: 'kg/m³', get: (o) => o.ssd.cement, tol: 0.5 },
    { label: 'Minimum cement content, 40 mm adjustment', ref: 'F-7', std: 210, unit: 'kg/m³', get: (o) => o.minCementitious, tol: 0 },
    { label: 'Volume of coarse aggregate', ref: 'F-8', std: 0.776, unit: '', get: (o) => o.caVolFraction, tol: 0.001 },
    { label: 'Volume of fine aggregate', ref: 'F-8', std: 0.224, unit: '', get: (o) => o.faVolFraction, tol: 0.001 },
    { label: 'Volume of all in aggregate', ref: 'F-9 (f)', std: 0.8053, unit: 'm³', get: (o) => o.volumes.vAgg, tol: 0.0002 },
    { label: 'Coarse aggregate, SSD', ref: 'F-9 (g)', std: 1712, unit: 'kg/m³', get: (o) => o.ssd.ca, tol: 0 },
    { label: 'Fine aggregate, SSD', ref: 'F-9 (h)', std: 478, unit: 'kg/m³', get: (o) => o.ssd.fa, tol: 0 },
    { label: 'Mortar content', ref: 'F-10', std: 0.375, unit: 'm³', get: (o) => o.mortar?.value, tol: 0.001 },
  ],
};

export const VERIFICATION_CASES = [ANNEX_A, ANNEX_B, ANNEX_C, ANNEX_D, ANNEX_E, ANNEX_F];

export function runVerification(vcase) {
  const out =
    vcase.input.section === 'scc'
      ? designSCC({ ...defaultInput('scc'), ...vcase.input })
      : designMix(vcase.input);
  const rows = vcase.expected.map((e) => {
    const calc = e.get(out);
    const delta = Number(calc) - Number(e.std);
    const exact = Math.abs(delta) < 1e-9;
    const pass = Math.abs(delta) <= (e.tol ?? 0) + 1e-9;
    return { ...e, calc, delta, exact, pass };
  });
  return {
    ...vcase,
    result: out,
    rows,
    passed: rows.filter((x) => x.pass).length,
    exact: rows.filter((x) => x.exact).length,
    total: rows.length,
    allPass: rows.every((x) => x.pass),
  };
}

export function runAllVerification() {
  return VERIFICATION_CASES.map(runVerification);
}
